### ISSUE TITLE
Not working with Ruby>Ruby1.9.1

### ISSUE THREAD

**Issue by qwertystud** [lutzky/ttime#25]
While trying to run ttime on Ubuntu 16.04, I'm getting the following error:
bash: /usr/bin/ttime: /usr/bin/ruby1.9.1: bad interpreter: No such file or directory

Using ruby 2.3 (wasn't able to install Ruby 1.9.1)

**Comment by lutzky** [comment]
Interesting. How are you installing? Probably not with a deb package, as the dependency would fail. Have you tried running directly from source? ruby1.9.1 is never explicitly mentioned in the code.

**Comment by qwertystud** [comment]
used the .deb package for version 0.9.5. never had any great luck installing from source, but i'll give it a shot

**Comment by qwertystud** [comment]
huh, running from source seems to work just fine.
I guess that's the solution

and no need for installing with configure/make. quite convenient.

thanks!!

**Comment by lutzky** [comment]
Not bad for an unmaintained piece of software :)
