### ISSUE TITLE
make ttime use REPY file instead of REPFILE.txt

### ISSUE THREAD

**Issue by qwertystud** [lutzky/ttime#26]
Hello there,
Is there a way to make ttime pull course datat from the REPY file provided by ug.technion?
It seems that currently ttime uses data from the REPFILE.txt packaged within the zip REP file. however, the txt file seems to have old 2015 spring semester data within it and the only file that's being updated by the Technion is the REPY file.

edit: notice how the REPFILE.zip package downloaded today contains a REPY file that was last modified on 14/01/2017 whereas the REPFILE.txt file was lsat modified on 14/01/**2015**

thanks for your help and hopefully this project will gain some momentum as currently, there aren't any good alternatives.

**Comment by lutzky** [comment]
This is now solved, also obsolescing #24. Thank you!
If you're using the Windows version, please try manually applying 2477789 to your local copy.
